#! /bin/bash

# Set globals
# *****************************
VERSION="0.1.0"
# *****************************
ARCH='aarch64'
CARCH=$(uname -m)
OS="SE Bastille installer"
TITLE="${OS} v${VERSION}"

# set colorscheme
export DIALOGRC="./dialogrc_gui"

# clearing variables
CONFIRMPASSWORD=""
CONFIRMROOTPASSWORD=""
CRYPT=""
DEVICE=""
DEV_NAME=""
FS_TYPE=""
FULLNAME=""
HOSTNAME=""
KEYMAP_CLI=""
KEYMAP_HOST=""
KEYVAR_HOST=""
LOCALE=""
PASSWORD=""
RESPONSE=""
ROOTPASSWORD=""
SD_DEV=""
SD_CARD=""
SD_TYPE=""
USER=""
USERGROUPS=""
TIMEZONE=""
URL=""

# check if root
if [ "$EUID" -ne 0 ]; then
    echo "*******************************************************************************************"
    echo "*                                                                                         *"
    echo "*     This script requires root permissions to run. Please run as root or with doas!      *"
    echo "*                                                                                         *"
    echo "*******************************************************************************************"
  exit
fi

# Sanity checks for dependencies
declare -a DEPENDENCIES=\
("git" "parted" "wget" "dialog" "openssl" "awk" "btrfs" "mkfs.vfat" "mkfs.btrfs")

for i in "${DEPENDENCIES[@]}"; do
  if ! [[ -f "/bin/$i" || -f "/sbin/$i" || -f "/usr/bin/$i" || -f "/usr/sbin/$i" ]] ; then
    echo "$i command is missing! Please install the relevant package."
    exit 1
  fi
done

# Functions
cleanup() {
  # edit boot files and fstab
  #
  if [[ "DEVICE" = "rpi4" ]]; then
    echo "===> Installing default config.txt file to /boot/..."
  fi
}

create_install() {
  msg "Creating install for $DEVICE..."
  info "Used device is ${SD_CARD}"

  # fetch and extract rootfs 
  info "Downloading latest $ARCH rootfs..."
  cd $TMP_DIR
  
  URL=$(wget -q -O https://armtixlinux.org/images) | grep dinit
  msg "Found url: $URL"
  # wget -q --show-progress --progress=bar:firce:noscroll https://armtixlinux.org/images/armtix-dinit-20230401.tar.xz 
}

elapsed_time(){
  echo $(echo $1 $(get_timer) | awk '{ printf "%0.2f",($2-$1)/60}')
}

dialog_fail() {
  case $RESPONSE in
    0)
      msg "$1"
      msg "Please restart the installer and try again."
      ;;
    1)
      msg "Cancel pressed, exiting.."
      ;;
    *)
      if [ ! -z "$1" ]; then
        msg "$1"
      else
        msg "Unknown error occured."
      fi
        msg "Please contact the administrator of this application."
      ;;
  esac
}

get_timer(){
  echo $(date +%s)
}

msg() {
  ALL_OFF="\e[1;0m"
  BOLD="\e[1;1m"
  GREEN="${BOLD}\e[1;32m"
  local mesg=$1; shift
  printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}

  prepare_card() {
  msg "Getting $SD_CARD ready with btrfs for $DEVICE..."

  # umount SD card
  umount ${SD_CARD}${SD_DEV}1 1> /dev/null 2>&1
  umount ${SD_CARD}${SD_DEV}2 1> /dev/null 2>&1
  # Create partitions
  # remove previous partitions
  for v_partition in $(parted -s $SD_CARD print|awk '/^ / {print $1}')
  do
    parted -s $SD_CARD rm ${v_partition} 1> /dev/null 2>&1
  done
  # Clear first 32mb
  # dd if=/dev/zero of=$SD_CARD bs=1M count=32 1> /dev/null 2>&1
}

show_elapsed_time() { 
  msg "Time %s: %s minutes..." "$1" "elapsed_time $2"
}

# Keymap host dialog
let i=0
W=()
while read -r line; do
  let i=$i+1
  W+=($line "")
  echo $line
done < <( ls /usr/share/bkeymaps )
KEYMAP_HOST=$(dialog --clear --title "${TITLE}" \
--menu "Choose your current keyboard layout:" \
20 50 15 "${W[@]}" 3>&1 1>&2 2>&3 3>&-)
RESPONSE=$?

# Keymap variant dialog 
if [ ! -z "$KEYMAP_HOST" ]; then
  let i=0
  W=()
  while read -r line; do
    let i=$i+1
    W+=($line "")
    echo $line
  done < <( ls /usr/share/bkeymaps/${KEYMAP_HOST} | sed -e 's/\.bmap\.gz$//' )
  KEYVAR_HOST=$(dialog --clear --title "${TITLE}" \
    --menu "Choose your current keyboard variant:" \
  20 50 15 "${W[@]}" 3>&1 1>&2 2>&3 3>&-)
  RESPONSE=$?
else
  clear
  dialog_fail
  exit 1
fi

# Username dialog 
if [ ! -z "$KEYVAR_HOST" ]; then
  # setup-keymap ${KEYMAP_HOST} ${KEYVAR_HOST}
  USER=$(dialog --clear --title "${TITLE}" \
    --inputbox "Enter the username you want: \
    (usernames must be all lowercase and first character may not be a number)" \
  10 90 "bas" --output-fd 1)
  RESPONSE=$?

  if [[ "$USER" =~ [A-Z] ]] || [[ "$USER" =~ ^[0-9] ]] || [[ "$USER" == *['!'@#\$%^\&*()_+]* ]]; then
    clear
    msg "${USER} Configuration aborted! Username contained invalid characters."
    exit 1
  fi
else
  clear
  dialog_fail
  exit 1
fi

# Additional usergroups dialog
if [ ! -z "$USER" ]; then
USERGROUPS=$(dialog --clear --title "${TITLE}" \
  --inputbox "Enter additional groups besides the default groups for $USER 
in a comma seperated list: 
(default: wheel,sys,audio,input,video,storage,lp,network,users,power)" 10 90 \
  --output-fd 1)
RESPONSE=$?
else
  clear
  dialog_fail "Configuration aborted! Username cannot be empty."  
  exit 1
fi

# Fullname dialog
FULLNAME=$(dialog --clear --title "${TITLE}" \
  --inputbox "Enter desired Full Name for $USER:" \
  8 50 "Useur Bastille" --output-fd 1)
RESPONSE=$?

if [ ! -z "$FULLNAME" ]; then
  PASSWORD=$(dialog --clear --title "${TITLE}" \
  --insecure --passwordbox "Enter new Password for $USER:" \
  8 50 3>&1 1>&2 2>&3 3>&-)
  RESPONSE=$?
else 
  clear
  dialog_fail
  exit 1
fi

if [ ! -z "$PASSWORD" ]; then
  CONFIRMPASSWORD=$(dialog --clear --title "${TITLE}" \
  --insecure --passwordbox "Confirm new Password for $USER:" \
  8 50 3>&1 1>&2 2>&3 3>&-)
  RESPONSE=$?
else 
  clear
  dialog_fail "Password cannot be empty."
  exit 1
fi

if [[ "$PASSWORD" != "$CONFIRMPASSWORD" ]]; then
  clear
  dialog_fail 0 "User passwords do not match!"
  exit 1
fi

if [ ! -z "$CONFIRMPASSWORD" ]; then
  ROOTPASSWORD=$(dialog --clear --title "${TITLE}" \
  --insecure --passwordbox "Enter new Root Password:" \
  8 50 3>&1 1>&2 2>&3 3>&-)
  RESPONSE=$?
else 
  clear
  dialog_fail RESPONSE "Confirmation password is empty. This error should not occur." ""
  exit 1
fi

if [ ! -z "$ROOTPASSWORD" ]; then
  CONFIRMROOTPASSWORD=$(dialog --clear --title "${TITLE}" \
  --insecure --passwordbox "Confirm new Root Password:" \
  8 50 3>&1 1>&2 2>&3 3>&-)
  RESPONSE=$?
else 
  clear
  dialog_fail
  exit 1
fi

if [[ "$ROOTPASSWORD" != "$CONFIRMROOTPASSWORD" ]]; then
    clear
    RESPONSE=0
    dialog_fail "Root passwords do not match!"
    exit 1
fi

# Drive dialog. 
# Uses simple command to put the results of lsblk 
# (just the names of the devices) 
# into an array and make that array populate the options	
if [ ! -z "$CONFIRMROOTPASSWORD" ]; then
    let i=0
    W=()
    while read -r line; do
      let i=$i+1
      W+=($line "")
    done < <( lsblk -dn -o NAME )
   
    if [[ ${#W[@]} -eq 0 ]]; then
      clear
      msg "Configuration aborted! No drive found."
      exit 1
    fi

    SD_CARD=$(dialog --title "${TITLE}" \
    --menu "Choose your SDCard/eMMC/USB - Be sure the correct drive is selected! 
    WARNING! This WILL destroy the data on it!" \
    20 50 10 "${W[@]}" 3>&2 2>&1 1>&3)

    DEV_NAME=$SD_CARD
    SD_CARD=/dev/$SD_CARD
    SD_TYPE=${SD_CARD:5:2}
    FS_TYPE="btrfs"
    RESPONSE=$?
else 
  clear
  dialog_fail
  exit 1
fi

if [[ "$SD_TYPE" = "sd" ]]; then
  SD_DEV=""
elif [[ "$SD_TYPE" = "mm" || "$SD_TYPE" = "nv" ]]; then
  SD_DEV="p"
else 
  clear
  dialog_fail "Unkown Block Device Type"
  exit 1
fi

if [ ! -z "$DEV_NAME" ]; then
  let i=0
  W=()
  while read -r line; do
    let i=$i+1
    W+=($line "")
  done < <( timedatectl list-timezones )
  TIMEZONE=$(dialog --clear --title "${TITLE}" \
    --menu "Choose your timezone!" 20 50 15 \
    "${W[@]}" 3>&1 1>&2 2>&3 3>&-)
  RESPONSE=$?
else 
  clear
  dialog_fail
  exit 1
fi

if [ ! -z "$TIMEZONE" ]; then
  let i=0
  W=()
  while read -r line; do
    let i=$i+1
    W+=($line "")
  done < <( cat /etc/locale.gen | grep "UTF-8" | tail -n +2 | sed -e 's/^#*//' | awk '{print $1}' )
  LOCALE=$(dialog --clear --title "${TITLE}" \
  --menu "Choose your locale!" \
  20 50 15 "${W[@]}" 3>&1 1>&2 2>&3 3>&-)
else 
  clear
  dialog_fail
  exit 1
fi

if [ ! -z "$LOCALE" ]; then
  let i=0
  W=()
  while read -r line; do
    let i=$i+1
    W+=($line "")
  done < <( localectl list-keymaps )
  KEYMAP_CLI=$(dialog --clear --title "${TITLE}" \
  --menu "Choose your TTY keyboard layout:" \
  20 50 15 "${W[@]}" 3>&1 1>&2 2>&3 3>&-)
  RESPONSE=$?
else 
  clear
  dialog_fail
  exit 1
fi

if [ ! -z "$KEYMAP_CLI" ]; then
  HOSTNAME=$(dialog --clear --title "${TITLE}" \
    --inputbox "Enter desired hostname for this system:" 8 50 \
    3>&1 1>&2 2>&3 3>&-)
  RESPONSE=$?
else 
  clear
  dialog_fail
  exit 1
fi

if [ ! -z "$HOSTNAME" ]; then
  dialog --clear --title "${TITLE}" \
  --yesno "Is the below information correct:
  Username = $USER
  Full Username = $FULLNAME
  Additional usergroups = $USERGROUPS
  Password for $USER = (password hidden)
  Password for root = (password hidden)
  SDCard/eMMC/USB = $SD_CARD
  Filesystem = $FS_TYPE
  Timezone = $TIMEZONE
  Locale = $LOCALE
  TTY Keyboard layout = $KEYMAP_CLI
  Hostname = $HOSTNAME" \
  25 70 3>&1 1>&2 2>&3 3>&-
else
  clear
  dialog_fail
  exit 1
fi

# Commands
timer_start=$(get_timer)

prepare_card
create_install
cleanup
show_elapsed_time "${FUNCNAME}" "${timer_start}"
sync
